# Generated by Django 2.1 on 2019-08-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0002_auto_20190816_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccine',
        ),
        migrations.AddField(
            model_name='cell',
            name='netzooLink',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='cell',
            name='netzooRel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cellLine',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cell',
            name='netzoo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cell',
            name='tool',
            field=models.CharField(max_length=200),
        ),
    ]
