# Generated by Django 2.1 on 2019-08-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0003_auto_20190816_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='netzooLink',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='cell',
            name='netzooRel',
            field=models.FloatField(),
        ),
    ]
