# Generated by Django 2.1 on 2019-08-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0004_auto_20190816_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cellLink',
            field=models.URLField(default='#'),
        ),
    ]
