# Generated by Django 2.1 on 2019-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0006_drug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tissue', models.CharField(max_length=200)),
                ('tissueLink', models.URLField(default='#')),
                ('tool', models.CharField(max_length=200)),
                ('netzoo', models.CharField(max_length=200)),
                ('netzooLink', models.URLField()),
                ('netzooRel', models.FloatField()),
                ('network', models.URLField()),
                ('ppi', models.URLField()),
                ('ppiLink', models.URLField()),
                ('motif', models.URLField()),
                ('expression', models.URLField()),
                ('expLink', models.URLField()),
                ('tfs', models.IntegerField()),
                ('genes', models.IntegerField()),
                ('refs', models.URLField()),
            ],
        ),
    ]
