# Generated by Django 2.1 on 2019-09-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0007_tissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='drugLink',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='expLink',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='netzooLink',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='netzooRel',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='ppiLink',
        ),
        migrations.AddField(
            model_name='drug',
            name='number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='drug',
            name='expression',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='drug',
            name='motif',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='drug',
            name='network',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='drug',
            name='netzoo',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='drug',
            name='ppi',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='drug',
            name='tool',
            field=models.CharField(max_length=400),
        ),
    ]
