# Generated by Django 2.1 on 2019-09-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0008_auto_20190904_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=400)),
                ('overlap', models.FloatField()),
                ('cosine', models.FloatField()),
            ],
        ),
    ]
