# Generated by Django 2.1 on 2019-09-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0009_drugresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugresult',
            name='idd',
            field=models.IntegerField(default='0'),
        ),
    ]
