# Generated by Django 2.1 on 2019-09-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0010_drugresult_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugresult',
            name='idd',
        ),
        migrations.AlterField(
            model_name='drugresult',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
