# Generated by Django 2.1 on 2019-09-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0011_auto_20190916_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugresult',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
