# Generated by Django 2.1 on 2019-09-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0013_auto_20190918_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genesupin', models.IntegerField()),
                ('genesdowin', models.IntegerField()),
                ('genesup', models.IntegerField()),
                ('genesdown', models.IntegerField()),
            ],
        ),
    ]
