# Generated by Django 2.1 on 2019-09-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0014_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='genesdowin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='params',
            name='genesdown',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='params',
            name='genesup',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='params',
            name='genesupin',
            field=models.IntegerField(null=True),
        ),
    ]
