# Generated by Django 2.1 on 2019-09-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0015_auto_20190919_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='params',
            name='genesdowin',
        ),
        migrations.AddField(
            model_name='params',
            name='genesdownin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='params',
            name='genesdown',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='params',
            name='genesup',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='params',
            name='genesupin',
            field=models.IntegerField(),
        ),
    ]
