# Generated by Django 2.1 on 2019-09-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0016_auto_20190919_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=600)),
                ('count', models.IntegerField()),
                ('intersect', models.IntegerField()),
                ('pval', models.FloatField()),
                ('qval', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gwas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=600)),
                ('count', models.IntegerField()),
                ('intersect', models.IntegerField()),
                ('pval', models.FloatField()),
                ('qval', models.FloatField()),
            ],
        ),
    ]
