# Generated by Django 2.1 on 2019-09-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0017_disease_gwas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugresultup',
            options={'ordering': ['overlap']},
        ),
    ]
