# Generated by Django 2.1 on 2019-09-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0018_auto_20190924_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugresultup',
            options={},
        ),
    ]
