# Generated by Django 2.1 on 2019-09-25 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0019_auto_20190924_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='drugresultup',
            name='query',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='drugsup', to='grandapp.Query'),
        ),
    ]
