# Generated by Django 2.1 on 2019-09-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0021_auto_20190925_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugresultup',
            name='query',
            field=models.IntegerField(default=0),
        ),
    ]
