# Generated by Django 2.1 on 2019-09-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0023_drugresultdown_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='query',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gwas',
            name='query',
            field=models.IntegerField(default=0),
        ),
    ]
