# Generated by Django 2.1 on 2019-10-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0024_auto_20190925_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissue',
            name='refs2',
            field=models.URLField(default='#'),
        ),
    ]
