# Generated by Django 3.0.2 on 2020-02-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0027_drugapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissue',
            name='nnets',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
