# Generated by Django 3.0.2 on 2020-02-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0028_tissue_nnets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tissue',
            name='nnets',
            field=models.IntegerField(default=0),
        ),
    ]
