# Generated by Django 3.0.2 on 2020-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0031_auto_20200219_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tissuelanding',
            name='nnets',
        ),
        migrations.AddField(
            model_name='tissuelanding',
            name='samples',
            field=models.IntegerField(default=0),
        ),
    ]
