# Generated by Django 3.0.2 on 2020-03-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0035_cell_samples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Druglanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('drug', models.CharField(max_length=200)),
                ('tool', models.CharField(max_length=200)),
                ('netzoo', models.CharField(max_length=200)),
                ('network', models.URLField()),
                ('ppi', models.URLField()),
                ('motif', models.URLField()),
                ('expression', models.URLField()),
                ('tfs', models.IntegerField()),
                ('genes', models.IntegerField()),
                ('refs', models.URLField()),
            ],
        ),
    ]
