# Generated by Django 3.0.2 on 2020-03-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0036_druglanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='druglanding',
            name='netzooRel',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
