# Generated by Django 3.0.2 on 2020-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0037_druglanding_netzoorel'),
    ]

    operations = [
        migrations.AddField(
            model_name='druglanding',
            name='ppiLink',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
