# Generated by Django 3.0.2 on 2020-03-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0038_druglanding_ppilink'),
    ]

    operations = [
        migrations.AddField(
            model_name='druglanding',
            name='samples',
            field=models.IntegerField(default=0),
        ),
    ]
