# Generated by Django 3.0.2 on 2020-03-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0039_druglanding_samples'),
    ]

    operations = [
        migrations.AddField(
            model_name='druglanding',
            name='cid',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
