# Generated by Django 3.0.2 on 2020-03-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0040_druglanding_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='druglanding',
            name='cid',
        ),
    ]
