# Generated by Django 3.0.2 on 2020-03-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0041_remove_druglanding_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='druglanding',
            name='expLink',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
