# Generated by Django 3.0.2 on 2020-04-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0042_druglanding_explink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrugApi',
        ),
    ]
