# Generated by Django 3.0.2 on 2020-04-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0043_delete_drugapi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugresultdown',
            name='query',
        ),
        migrations.RemoveField(
            model_name='drugresultup',
            name='query',
        ),
    ]
