# Generated by Django 3.0.2 on 2020-04-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0045_auto_20200403_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='query',
        ),
        migrations.AddField(
            model_name='disease',
            name='hpoId',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
