# Generated by Django 3.0.2 on 2020-04-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0047_auto_20200404_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='query',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugresultdown',
            name='query',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugresultup',
            name='query',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gwas',
            name='query',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='params',
            name='query',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissueex',
            name='query',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissuetar',
            name='query',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
