# Generated by Django 3.0.2 on 2020-04-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0048_auto_20200410_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='query',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drugresultdown',
            name='query',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drugresultup',
            name='query',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gwas',
            name='query',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='params',
            name='query',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tissueex',
            name='query',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tissuetar',
            name='query',
            field=models.IntegerField(default=0),
        ),
    ]
