# Generated by Django 3.0.2 on 2020-04-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0049_auto_20200410_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='genesdown',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='params',
            name='genesup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='params',
            name='genesupin',
            field=models.IntegerField(default=0),
        ),
    ]
