# Generated by Django 3.0.2 on 2020-04-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0050_auto_20200410_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
