# Generated by Django 3.0.5 on 2020-04-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0051_auto_20200410_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tissuesample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleid', models.CharField(max_length=600)),
                ('subjectid', models.CharField(max_length=600)),
                ('tissueid', models.CharField(max_length=600)),
                ('gender', models.IntegerField(default=0)),
                ('age', models.CharField(max_length=600)),
                ('dthhrdy', models.IntegerField(default=0)),
                ('smatsscr', models.IntegerField(default=0)),
                ('smrin', models.FloatField()),
                ('smts', models.CharField(max_length=600)),
                ('smtsd', models.CharField(max_length=600)),
                ('smubrid', models.IntegerField(default=0)),
                ('smtsisch', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='params',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
