# Generated by Django 3.0.5 on 2020-04-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0052_auto_20200419_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tissuesample',
            name='dthhrdy',
            field=models.CharField(max_length=600),
        ),
    ]
