# Generated by Django 3.0.5 on 2020-04-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0055_auto_20200419_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tissuesample',
            name='smtsisch',
            field=models.CharField(max_length=600),
        ),
    ]
