# Generated by Django 3.0.5 on 2020-04-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0056_auto_20200419_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuesample',
            name='grdid',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
