# Generated by Django 3.0.5 on 2020-04-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0058_tissuesample_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tissuesample',
            name='gender',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='tissuesample',
            name='smrin',
            field=models.CharField(max_length=600),
        ),
    ]
