# Generated by Django 3.0.5 on 2020-04-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0059_auto_20200419_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuesample',
            name='link',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
