# Generated by Django 3.0.5 on 2020-04-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0060_tissuesample_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='nuser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gwas',
            name='nuser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tissueex',
            name='nuser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tissuetar',
            name='nuser',
            field=models.IntegerField(default=0),
        ),
    ]
