# Generated by Django 3.0.5 on 2020-04-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0061_auto_20200426_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='idd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disease',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
