# Generated by Django 3.0.5 on 2020-04-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0064_auto_20200426_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='netzooRel',
            field=models.CharField(max_length=200),
        ),
    ]
