# Generated by Django 3.0.2 on 2020-05-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0067_tcgasample'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerlanding',
            name='cardref',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
