# Generated by Django 3.0.2 on 2020-05-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0068_cancerlanding_cardref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geosample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200)),
                ('geoID', models.CharField(max_length=200)),
                ('age_at_initial_pathologic_diagnosis', models.CharField(max_length=200)),
                ('tumor_location', models.CharField(max_length=200)),
                ('uicc_stage', models.CharField(max_length=200)),
                ('time_to_event', models.CharField(max_length=200)),
                ('vital_status', models.CharField(max_length=200)),
            ],
        ),
    ]
