# Generated by Django 3.0.2 on 2020-05-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0069_geosample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geosample',
            old_name='geoID',
            new_name='geoid',
        ),
    ]
