# Generated by Django 3.0.2 on 2020-05-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0070_auto_20200504_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcgasample',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcgasample',
            name='size',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
