# Generated by Django 3.0.2 on 2020-05-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0071_auto_20200505_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='geosample',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geosample',
            name='size',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
