# Generated by Django 3.0.2 on 2020-05-06 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0072_auto_20200505_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancerlanding',
            old_name='tissue',
            new_name='cancer',
        ),
        migrations.RenameField(
            model_name='cancerlanding',
            old_name='tissueLink',
            new_name='cancerLink',
        ),
    ]
