# Generated by Django 3.0.5 on 2020-05-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0073_auto_20200506_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genelanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_gene_id', models.CharField(max_length=200)),
                ('pr_gene_symbol', models.CharField(max_length=200)),
                ('pr_gene_title', models.CharField(max_length=200)),
                ('pr_is_lm', models.CharField(max_length=200)),
                ('pr_is_bing', models.CharField(max_length=200)),
            ],
        ),
    ]
