# Generated by Django 3.0.5 on 2020-05-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0074_genelanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugsample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig_id', models.CharField(max_length=200)),
                ('pert_iname', models.CharField(max_length=200)),
                ('cell_id', models.CharField(max_length=200)),
                ('pert_idose', models.CharField(max_length=200)),
                ('pert_itime', models.CharField(max_length=200)),
                ('distil_nsample', models.CharField(max_length=200)),
                ('cell_type', models.CharField(max_length=200)),
                ('modification', models.CharField(max_length=200)),
                ('sample_type', models.CharField(max_length=200)),
                ('primary_site', models.CharField(max_length=200)),
                ('subtype', models.CharField(max_length=200)),
                ('original_growth_pattern', models.CharField(max_length=200)),
                ('donor_age', models.CharField(max_length=200)),
                ('donor_sex', models.CharField(max_length=200)),
                ('donor_ethnicity', models.CharField(max_length=200)),
            ],
        ),
    ]
