# Generated by Django 3.0.5 on 2020-05-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0075_drugsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugsample',
            name='network',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugsample',
            name='size',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
