# Generated by Django 3.0.5 on 2020-05-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0076_auto_20200517_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugdesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_mass', models.CharField(max_length=200)),
                ('smiles', models.CharField(max_length=200)),
                ('InChIKey', models.CharField(max_length=200)),
                ('pubchem_cid', models.CharField(max_length=200)),
                ('pert_iname', models.CharField(max_length=200)),
                ('clinical_phase', models.CharField(max_length=200)),
                ('moa', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=200)),
                ('disease_area', models.CharField(max_length=200)),
                ('indication', models.CharField(max_length=200)),
            ],
        ),
    ]
