# Generated by Django 3.0.5 on 2020-05-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0077_drugdesc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.AddField(
            model_name='druglanding',
            name='nnets',
            field=models.IntegerField(default=0),
        ),
    ]
