# Generated by Django 3.0.5 on 2020-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0078_auto_20200519_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='druglanding',
            name='druglink',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
