# Generated by Django 3.0.5 on 2020-05-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0079_druglanding_druglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugdesc',
            name='broad_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
