# Generated by Django 3.0.2 on 2020-06-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0081_drugsample_infl'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugsample',
            name='links',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugsample',
            name='linksTF',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
