# Generated by Django 3.0.5 on 2020-06-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0082_auto_20200601_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tissue', models.CharField(max_length=200)),
                ('nnets', models.IntegerField(default=0)),
            ],
        ),
    ]
