# Generated by Django 3.0.5 on 2020-06-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0083_cancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuelanding',
            name='reg',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
