# Generated by Django 3.0.5 on 2020-06-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0084_tissuelanding_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuelanding',
            name='motifDesc',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
