# Generated by Django 3.0.5 on 2020-07-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0085_tissuelanding_motifdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuelanding',
            name='script',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
