# Generated by Django 3.0.5 on 2020-07-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0086_tissuelanding_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerlanding',
            name='scriptf',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
