# Generated by Django 3.0.5 on 2020-07-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0087_cancerlanding_scriptf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancerlanding',
            old_name='scriptf',
            new_name='script',
        ),
    ]
