# Generated by Django 3.0.5 on 2020-07-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0088_auto_20200702_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='script',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
