# Generated by Django 3.0.5 on 2020-07-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0089_cell_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breastsample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200)),
                ('weight_kg_at_diagnosis', models.CharField(max_length=200)),
                ('height_cm_at_diagnosis', models.CharField(max_length=200)),
                ('age_at_initial_pathologic_diagnosis', models.CharField(max_length=200)),
                ('anatomic_neoplasm_subdivision', models.CharField(max_length=200)),
                ('uicc_stage', models.CharField(max_length=200)),
                ('time_to_event', models.CharField(max_length=200)),
                ('vital_status', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
