# Generated by Django 3.0.5 on 2020-07-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0090_breastsample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breastsample',
            name='platform',
        ),
    ]
