# Generated by Django 3.0.5 on 2020-07-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0091_remove_breastsample_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breastsample',
            old_name='anatomic_neoplasm_subdivision',
            new_name='ethnicity',
        ),
        migrations.RenameField(
            model_name='breastsample',
            old_name='link',
            new_name='primary_diagnosis',
        ),
        migrations.RenameField(
            model_name='breastsample',
            old_name='size',
            new_name='primary_site',
        ),
    ]
