# Generated by Django 3.0.5 on 2020-07-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0092_auto_20200730_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cervixsample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200)),
                ('ethnicity', models.CharField(max_length=200)),
                ('weight_kg_at_diagnosis', models.CharField(max_length=200)),
                ('height_cm_at_diagnosis', models.CharField(max_length=200)),
                ('age_at_initial_pathologic_diagnosis', models.CharField(max_length=200)),
                ('primary_site', models.CharField(max_length=200)),
                ('primary_diagnosis', models.CharField(max_length=200)),
                ('uicc_stage', models.CharField(max_length=200)),
                ('time_to_event', models.CharField(max_length=200)),
                ('vital_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Liversample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200)),
                ('ethnicity', models.CharField(max_length=200)),
                ('weight_kg_at_diagnosis', models.CharField(max_length=200)),
                ('height_cm_at_diagnosis', models.CharField(max_length=200)),
                ('age_at_initial_pathologic_diagnosis', models.CharField(max_length=200)),
                ('primary_site', models.CharField(max_length=200)),
                ('primary_diagnosis', models.CharField(max_length=200)),
                ('uicc_stage', models.CharField(max_length=200)),
                ('time_to_event', models.CharField(max_length=200)),
                ('vital_status', models.CharField(max_length=200)),
            ],
        ),
    ]
