# Generated by Django 3.0.2 on 2021-01-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0094_cancer_datasets'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancer',
            name='types',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cancer',
            name='nnets',
            field=models.CharField(max_length=200),
        ),
    ]
