# Generated by Django 3.0.2 on 2021-01-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0095_auto_20210122_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuelanding',
            name='refs3',
            field=models.URLField(default='#'),
        ),
    ]
