# Generated by Django 3.0.2 on 2021-02-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0097_auto_20210219_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwas',
            name='logpval',
            field=models.FloatField(default=10.1),
            preserve_default=False,
        ),
    ]
