# Generated by Django 3.0.2 on 2021-02-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0098_gwas_logpval'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='logpval',
            field=models.FloatField(default=10.1),
            preserve_default=False,
        ),
    ]
