# Generated by Django 3.0.2 on 2021-02-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0099_disease_logpval'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissueex',
            name='logpval',
            field=models.FloatField(default=10.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissuetar',
            name='logpval',
            field=models.FloatField(default=10.1),
            preserve_default=False,
        ),
    ]
