# Generated by Django 3.0.2 on 2021-02-24 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0103_auto_20210223_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ggbmd1sample',
            old_name='ethnicitity',
            new_name='ethnicity',
        ),
        migrations.RenameField(
            model_name='ggbmd2sample',
            old_name='ethnicitity',
            new_name='ethnicity',
        ),
    ]
