# Generated by Django 3.0.2 on 2021-02-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0105_auto_20210224_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ggnsample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survival', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
