# Generated by Django 3.0.2 on 2021-02-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0106_ggnsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggnsample',
            name='sample',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
