# Generated by Django 3.0.2 on 2021-03-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0107_ggnsample_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pancreassample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('primary_site', models.CharField(max_length=200)),
                ('ethnicity', models.CharField(max_length=200)),
                ('primary_diagnosis', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=200)),
                ('daystodeath', models.CharField(max_length=200)),
                ('vital_status', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('subtype', models.CharField(max_length=200)),
            ],
        ),
    ]
