# Generated by Django 3.0.2 on 2021-03-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0108_pancreassample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pancreassample',
            old_name='age',
            new_name='age_at_initial_pathologic_diagnosis',
        ),
        migrations.RenameField(
            model_name='pancreassample',
            old_name='daystodeath',
            new_name='time_to_event',
        ),
        migrations.RenameField(
            model_name='pancreassample',
            old_name='stage',
            new_name='uicc_stage',
        ),
    ]
