# Generated by Django 3.0.2 on 2021-03-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0109_auto_20210306_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='ggbmd1sample',
            name='platform',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ggbmd2sample',
            name='platform',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
