# Generated by Django 3.0.2 on 2021-03-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0110_auto_20210307_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugresultdown',
            name='orig',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugresultup',
            name='orig',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
