# Generated by Django 3.0.2 on 2021-03-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0111_auto_20210308_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Babeledges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromEdge', models.IntegerField()),
                ('to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Babelnodes',
            fields=[
                ('label', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
