# Generated by Django 3.0.2 on 2021-03-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0112_babeledges_babelnodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Babeledges',
        ),
        migrations.DeleteModel(
            name='Babelnodes',
        ),
    ]
