# Generated by Django 3.0.2 on 2021-03-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0113_auto_20210317_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topbottom', models.CharField(choices=[('Largest', 'Largest'), ('Smallest', 'Smallest')], max_length=200)),
                ('methyl', models.BooleanField()),
                ('mir', models.BooleanField()),
                ('exp', models.BooleanField()),
                ('prot', models.BooleanField()),
                ('met', models.BooleanField()),
                ('agg', models.BooleanField()),
                ('nedges', models.IntegerField()),
            ],
        ),
    ]
