# Generated by Django 3.0.2 on 2021-03-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0114_lala'),
    ]

    operations = [
        migrations.AddField(
            model_name='lala',
            name='absval',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
