# Generated by Django 3.0.2 on 2021-03-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0116_auto_20210318_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='lala',
            name='allay',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lala',
            name='connex',
            field=models.CharField(choices=[('Methylation', 'Methylation'), ('miRNA', 'miRNA'), ('mRNA', 'mRNA'), ('Protein', 'Protein'), ('Metabolism', 'Metabolism')], max_length=200),
        ),
    ]
