# Generated by Django 3.0.2 on 2021-03-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0118_lala_cnv'),
    ]

    operations = [
        migrations.AddField(
            model_name='lala',
            name='hm',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lala',
            name='connex',
            field=models.CharField(choices=[('Histone', 'Histone'), ('CNV', 'CNV'), ('Methylation', 'Methylation'), ('miRNA', 'miRNA'), ('mRNA', 'mRNA'), ('Protein', 'Protein'), ('Metabolism', 'Metabolism'), ('Drugs', 'Drugs')], max_length=200),
        ),
    ]
