# Generated by Django 3.0.2 on 2021-03-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0119_auto_20210323_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='lala',
            name='dep',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
