# Generated by Django 3.0.2 on 2021-03-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0120_lala_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lala',
            name='connex',
            field=models.CharField(choices=[('Histone', 'Histone'), ('CNV', 'CNV'), ('Methylation', 'Methylation'), ('miRNA', 'miRNA'), ('mRNA', 'mRNA'), ('Protein', 'Protein'), ('Metabolism', 'Metabolism'), ('Drugs', 'Drugs'), ('Dependency', 'Dependency')], max_length=200),
        ),
    ]
