# Generated by Django 3.0.2 on 2021-04-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0121_auto_20210327_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='netmod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.CharField(choices=[('no', ''), ('dtt', ''), ('dee', '')], max_length=200)),
                ('topbottom', models.CharField(choices=[('Largest', 'Largest'), ('Smallest', 'Smallest')], max_length=200)),
                ('brd', models.BooleanField()),
                ('nedges', models.IntegerField()),
            ],
        ),
    ]
