# Generated by Django 3.0.2 on 2021-04-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0122_netmod'),
    ]

    operations = [
        migrations.AddField(
            model_name='netmod',
            name='absval',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
