# Generated by Django 3.0.2 on 2021-04-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0125_auto_20210407_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netmod',
            name='genesel',
        ),
        migrations.RemoveField(
            model_name='netmod',
            name='tfsel',
        ),
        migrations.AddField(
            model_name='drugresultdown',
            name='pval',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugresultdown',
            name='qval',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugresultdown',
            name='tval',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugresultup',
            name='pval',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugresultup',
            name='qval',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugresultup',
            name='tval',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='netmod',
            name='tfgenesel',
            field=models.CharField(choices=[('nosel', 'nosel'), ('by gene', 'by gene'), ('by tf', 'by tf')], default=0.1, max_length=200),
            preserve_default=False,
        ),
    ]
