# Generated by Django 3.0.2 on 2021-04-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0126_auto_20210409_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugresultdown',
            name='pval',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='drugresultdown',
            name='qval',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='drugresultdown',
            name='tval',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='drugresultup',
            name='pval',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='drugresultup',
            name='qval',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='drugresultup',
            name='tval',
            field=models.FloatField(default=0.1),
        ),
    ]
