# Generated by Django 3.0.2 on 2021-04-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0127_auto_20210409_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='params',
            name='combin',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
