# Generated by Django 3.0.2 on 2021-04-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0128_params_combin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugcombsdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug1', models.CharField(max_length=400)),
                ('drug2', models.CharField(max_length=400)),
                ('cosine', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='Drugcombsup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug1', models.CharField(max_length=400)),
                ('drug2', models.CharField(max_length=400)),
                ('cosine', models.FloatField(default=0.1)),
            ],
        ),
    ]
