# Generated by Django 3.0.2 on 2021-04-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0131_auto_20210410_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugcombsdown',
            name='abscosine',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='drugcombsup',
            name='abscosine',
            field=models.FloatField(default=0.1),
        ),
    ]
