# Generated by Django 3.0.2 on 2021-04-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0132_auto_20210411_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gobp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=400)),
                ('goid', models.CharField(max_length=400)),
                ('genelist', models.CharField(max_length=1000)),
            ],
        ),
    ]
