# Generated by Django 3.0.2 on 2021-04-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0133_gobp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gobp',
            name='genelist',
            field=models.CharField(max_length=3000),
        ),
    ]
