# Generated by Django 3.0.2 on 2021-04-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0134_auto_20210411_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmod',
            name='tfgenesel',
            field=models.CharField(choices=[('nosel', 'nosel'), ('by gene', 'by gene'), ('by tf', 'by tf'), ('by GO', 'by GO')], max_length=200),
        ),
    ]
