# Generated by Django 3.0.2 on 2021-04-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0135_auto_20210411_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='gobp',
            name='idd',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
