# Generated by Django 3.0.2 on 2021-04-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0136_gobp_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gobp',
            name='idd',
            field=models.IntegerField(),
        ),
    ]
