# Generated by Django 3.0.2 on 2021-04-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0137_auto_20210412_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='netmod',
            name='goform',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
