# Generated by Django 3.0.2 on 2021-04-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0138_netmod_goform'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancer',
            name='nnets2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancer',
            name='nnets2ref',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancer',
            name='nnetsref',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
