# Generated by Django 3.0.2 on 2021-04-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0139_auto_20210412_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancer',
            name='datasets2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancer',
            name='datasets2ref',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancer',
            name='datasetsref',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
