# Generated by Django 3.0.2 on 2021-04-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0140_auto_20210412_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celllanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellLine', models.CharField(max_length=200)),
                ('cellLink', models.URLField(default='#')),
                ('tool', models.CharField(max_length=200)),
                ('netzoo', models.CharField(max_length=200)),
                ('netzooLink', models.URLField()),
                ('netzooRel', models.CharField(max_length=200)),
                ('network', models.URLField()),
                ('ppi', models.URLField()),
                ('ppiLink', models.URLField()),
                ('motif', models.URLField()),
                ('expression', models.URLField()),
                ('expLink', models.URLField()),
                ('tfs', models.IntegerField()),
                ('genes', models.IntegerField()),
                ('refs', models.URLField()),
                ('samples', models.IntegerField(default=0)),
                ('script', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='cell',
            old_name='genes',
            new_name='ncells',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='cellLine',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='cellLink',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='expLink',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='expression',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='motif',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='network',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='netzoo',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='netzooLink',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='netzooRel',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='ppi',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='ppiLink',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='refs',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='samples',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='script',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='tfs',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='tool',
        ),
        migrations.AddField(
            model_name='cell',
            name='disease',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
