# Generated by Django 3.0.2 on 2021-04-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0141_auto_20210413_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tissue', models.CharField(max_length=400)),
                ('method', models.CharField(max_length=400)),
                ('data', models.CharField(max_length=400)),
                ('typenet', models.CharField(max_length=400)),
                ('condition', models.CharField(max_length=400)),
            ],
        ),
    ]
