# Generated by Django 3.0.2 on 2021-04-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0142_cellpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellpage',
            name='datarefs',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cellpage',
            name='methodrefs',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
