# Generated by Django 3.0.2 on 2021-04-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0143_auto_20210414_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celllanding',
            old_name='cellLine',
            new_name='cancer',
        ),
        migrations.RenameField(
            model_name='celllanding',
            old_name='cellLink',
            new_name='cancerLink',
        ),
        migrations.AddField(
            model_name='celllanding',
            name='cardref',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celllanding',
            name='dataset',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celllanding',
            name='refs2',
            field=models.URLField(default='#'),
        ),
    ]
