# Generated by Django 3.0.2 on 2021-04-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0144_auto_20210414_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellpage',
            name='urllinks',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
