# Generated by Django 3.0.2 on 2021-04-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0146_cancer_cancerref'),
    ]

    operations = [
        migrations.AddField(
            model_name='celllanding',
            name='cancerref',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
