# Generated by Django 3.0.2 on 2021-04-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0148_celllanding_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellpage',
            name='reg',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
