# Generated by Django 3.0.2 on 2021-04-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0149_cellpage_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellsample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depmap', models.CharField(max_length=400)),
                ('stripcellname', models.CharField(max_length=400)),
                ('cclename', models.CharField(max_length=400)),
                ('cosmicid', models.CharField(max_length=400)),
                ('sex', models.CharField(max_length=400)),
                ('source', models.CharField(max_length=400)),
                ('culture', models.CharField(max_length=400)),
                ('cas9act', models.FloatField()),
                ('collsite', models.CharField(max_length=400)),
                ('prim', models.CharField(max_length=400)),
                ('disease', models.CharField(max_length=400)),
                ('subtype', models.CharField(max_length=400)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
