# Generated by Django 3.0.2 on 2021-04-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0150_cellsample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellsample',
            name='age',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='cellsample',
            name='cas9act',
            field=models.CharField(max_length=400),
        ),
    ]
