# Generated by Django 3.0.2 on 2021-04-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0151_auto_20210415_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellsample',
            name='doublt',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cellsample',
            name='mutrate',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
