# Generated by Django 3.0.2 on 2021-04-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0152_auto_20210416_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellsample',
            name='link',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cellsample',
            name='race',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cellsample',
            name='tcga',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
