# Generated by Django 3.0.2 on 2021-04-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0153_auto_20210416_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellsample',
            name='size',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
