# Generated by Django 3.0.2 on 2021-04-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0154_cellsample_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarmod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topbottom', models.CharField(choices=[('Largest', 'Largest'), ('Smallest', 'Smallest')], max_length=200)),
                ('nedges', models.IntegerField()),
                ('absval', models.BooleanField()),
            ],
        ),
    ]
