# Generated by Django 3.0.2 on 2021-04-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0155_tarmod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarmod',
            old_name='absval',
            new_name='absvaltar',
        ),
        migrations.RenameField(
            model_name='tarmod',
            old_name='nedges',
            new_name='nedgestar',
        ),
        migrations.RenameField(
            model_name='tarmod',
            old_name='topbottom',
            new_name='topbottomtar',
        ),
    ]
