# Generated by Django 3.0.2 on 2021-04-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0156_auto_20210416_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarmod',
            name='absvaltartf',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarmod',
            name='nedgestartf',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarmod',
            name='topbottomtartf',
            field=models.CharField(choices=[('Largest', 'Largest'), ('Smallest', 'Smallest')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
