# Generated by Django 3.0.2 on 2021-04-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0158_gobpbygene'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gwascata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=400)),
                ('genelist', models.CharField(max_length=3000)),
                ('idd', models.IntegerField()),
            ],
        ),
    ]
