# Generated by Django 3.0.2 on 2021-04-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0159_gwascata'),
    ]

    operations = [
        migrations.AddField(
            model_name='netmod',
            name='gwasform',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='netmod',
            name='tfgenesel',
            field=models.CharField(choices=[('nosel', 'nosel'), ('by gene', 'by gene'), ('by tf', 'by tf'), ('by GO', 'by GO'), ('by GWAS', 'by GWAS')], max_length=200),
        ),
    ]
