# Generated by Django 3.0.2 on 2021-04-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0161_gwascatabygene'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuesample',
            name='smtstptref',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
