# Generated by Django 3.0.2 on 2021-04-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0162_tissuesample_smtstptref'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellpage',
            name='method2',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cellpage',
            name='methodrefs2',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
