# Generated by Django 3.0.2 on 2021-04-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0163_auto_20210417_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellpage',
            name='reg2',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
