# Generated by Django 3.0.2 on 2021-04-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0164_cellpage_reg2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmod',
            name='dt',
            field=models.CharField(choices=[('no', ''), ('dtt', ''), ('dee', ''), ('bc', '')], max_length=200),
        ),
    ]
