# Generated by Django 3.0.2 on 2021-04-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0165_auto_20210418_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otterac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aurocbr', models.FloatField()),
                ('auroccer', models.FloatField()),
                ('aurocliv', models.FloatField()),
                ('auprbr', models.FloatField()),
                ('auprcer', models.FloatField()),
                ('auprliv', models.FloatField()),
            ],
        ),
    ]
