# Generated by Django 3.0.2 on 2021-04-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0166_otterac'),
    ]

    operations = [
        migrations.AddField(
            model_name='otterac',
            name='method',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
