# Generated by Django 3.0.2 on 2021-04-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0170_auto_20210419_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarmod',
            old_name='geneform',
            new_name='geneformtar',
        ),
        migrations.RenameField(
            model_name='tarmod',
            old_name='goform',
            new_name='goformtar',
        ),
        migrations.RenameField(
            model_name='tarmod',
            old_name='gwasform',
            new_name='gwasformtar',
        ),
        migrations.RenameField(
            model_name='tarmod',
            old_name='tfform',
            new_name='tfformtar',
        ),
        migrations.RenameField(
            model_name='tarmod',
            old_name='tfgenesel',
            new_name='tfgeneseltar',
        ),
    ]
