# Generated by Django 3.0.2 on 2021-04-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0171_auto_20210419_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarmod',
            name='tfformtar',
        ),
        migrations.AlterField(
            model_name='tarmod',
            name='tfgeneseltar',
            field=models.CharField(choices=[('nosel', 'nosel'), ('by gene', 'by gene'), ('by GO', 'by GO'), ('by GWAS', 'by GWAS')], max_length=200),
        ),
    ]
