# Generated by Django 3.0.2 on 2021-04-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0173_sendto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendto',
            name='genelist',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
