# Generated by Django 3.0.2 on 2021-04-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0174_sendto_genelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendto',
            old_name='genelist',
            new_name='genelistdown',
        ),
        migrations.AddField(
            model_name='sendto',
            name='genelistup',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
