# Generated by Django 3.0.2 on 2021-04-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0175_auto_20210420_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluemod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfgeneselclue', models.CharField(choices=[('by gene', 'by gene'), ('by tf', 'by tf')], max_length=200)),
            ],
        ),
    ]
