# Generated by Django 3.0.2 on 2021-04-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0177_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='idd',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
