# Generated by Django 3.0.2 on 2021-04-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0180_auto_20210423_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tissuesample',
            old_name='smrdlgth',
            new_name='smgnsdtc',
        ),
    ]
