# Generated by Django 3.0.2 on 2021-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0181_auto_20210423_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='celllanding',
            name='dummy',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
