# Generated by Django 3.0.2 on 2021-04-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0182_celllanding_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celllanding',
            name='dummy',
        ),
        migrations.AddField(
            model_name='cellsample',
            name='dummy',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
