# Generated by Django 3.0.2 on 2021-04-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0183_auto_20210423_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissue',
            name='nettype',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissue',
            name='reftool1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissue',
            name='reftool2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissue',
            name='reftool3',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissue',
            name='reg',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissue',
            name='tissuename',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissue',
            name='tool',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
