# Generated by Django 3.0.2 on 2021-04-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0184_auto_20210424_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tissue',
            old_name='tool',
            new_name='tool1',
        ),
        migrations.AddField(
            model_name='tissue',
            name='tool2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissue',
            name='tool3',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
