# Generated by Django 3.0.2 on 2021-04-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0185_auto_20210424_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissue',
            name='nsamples',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
