# Generated by Django 3.0.2 on 2021-04-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0186_tissue_nsamples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tissueac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko', models.FloatField()),
                ('cc', models.FloatField()),
                ('method', models.CharField(max_length=200)),
            ],
        ),
    ]
