# Generated by Django 3.0.2 on 2021-04-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0188_cellsample_presexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellsample',
            name='diffexp',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
