# Generated by Django 3.0.2 on 2021-04-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0189_cellsample_diffexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellsample',
            name='diffexpgenes',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
