# Generated by Django 3.0.2 on 2021-04-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0190_cellsample_diffexpgenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellsample',
            name='difftar',
            field=models.CharField(default=10, max_length=400),
            preserve_default=False,
        ),
    ]
