# Generated by Django 3.0.2 on 2021-04-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0191_cellsample_difftar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellsample',
            name='difftargenes',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
