# Generated by Django 3.0.2 on 2021-04-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0193_netmod_edgetargeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellsample',
            name='cleanname',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
