# Generated by Django 3.0.2 on 2021-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0194_cellsample_cleanname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuelanding',
            name='awsname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
