# Generated by Django 3.0.2 on 2021-04-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0195_tissuelanding_awsname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuesample',
            name='cleanname',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
