# Generated by Django 3.0.2 on 2021-04-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0196_tissuesample_cleanname'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugsample',
            name='diffexp',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugsample',
            name='diffexpgenes',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugsample',
            name='difftar',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugsample',
            name='difftargenes',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
