# Generated by Django 3.0.2 on 2021-04-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0197_auto_20210429_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugsample',
            name='avggenetar',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugsample',
            name='avgtftar',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drugsample',
            name='nsamples',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
