# Generated by Django 3.0.2 on 2021-04-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0198_auto_20210430_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugsample',
            name='avggenetar',
        ),
        migrations.RemoveField(
            model_name='drugsample',
            name='avgtftar',
        ),
        migrations.RemoveField(
            model_name='drugsample',
            name='nsamples',
        ),
        migrations.AddField(
            model_name='druglanding',
            name='avggenetar',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='druglanding',
            name='avgtftar',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='druglanding',
            name='nsamples',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
