# Generated by Django 3.0.2 on 2021-04-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0199_auto_20210430_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugsample',
            name='cleannames',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
