# Generated by Django 3.0.2 on 2021-05-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0200_drugsample_cleannames'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellsample',
            name='cleannamedis',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
