# Generated by Django 3.0.2 on 2021-05-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0201_cellsample_cleannamedis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancer',
            old_name='subtype',
            new_name='cancer',
        ),
        migrations.AddField(
            model_name='cancer',
            name='match',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancer',
            name='ngenes',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancer',
            name='nsamples',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancer',
            name='ntfs',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancer',
            name='tcgacode',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
