# Generated by Django 3.0.2 on 2021-05-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0206_cancerpheno_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancerpheno',
            old_name='age_at_initial_pathologic_diagnosis',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='cancerpheno',
            old_name='ajcc_pathologic_tumor_stage',
            new_name='ajcc',
        ),
    ]
