# Generated by Django 3.0.2 on 2021-05-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0207_auto_20210504_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellsample',
            name='isdragon',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
