# Generated by Django 3.0.2 on 2021-05-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0209_enrichgenes_enrichtfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='compmod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp1', models.CharField(choices=[('nosel', 'nosel'), ('by gene', 'by gene')], max_length=200)),
                ('comp2', models.CharField(choices=[('nosel', 'nosel'), ('by gene', 'by gene')], max_length=200)),
                ('dt', models.CharField(choices=[('no', ''), ('dtt', ''), ('dee', ''), ('bc', '')], max_length=200)),
                ('topbottom', models.CharField(choices=[('Largest', 'Largest'), ('Smallest', 'Smallest')], max_length=200)),
                ('brd', models.BooleanField()),
                ('nedges', models.IntegerField()),
                ('absval', models.BooleanField()),
                ('edgetargeting', models.BooleanField()),
                ('tfgenesel', models.CharField(choices=[('nosel', 'nosel'), ('by gene', 'by gene'), ('by tf', 'by tf'), ('by GO', 'by GO'), ('by GWAS', 'by GWAS')], max_length=200)),
                ('geneform', models.CharField(max_length=200)),
                ('tfform', models.CharField(max_length=200)),
                ('goform', models.CharField(max_length=200)),
                ('gwasform', models.CharField(max_length=200)),
            ],
        ),
    ]
