# Generated by Django 3.0.2 on 2021-05-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0210_compmod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compmod',
            name='comp1',
            field=models.CharField(choices=[('Adipose_Subcutaneous', 'Adipose_Subcutaneous'), ('Adipose_Visceral', 'Adipose_Visceral'), ('Adrenal_Gland', 'Adrenal_Gland'), ('Artery_Aorta', 'Artery_Aorta'), ('Artery_Coronary', 'Artery_Coronary'), ('Artery_Tibial', 'Artery_Tibial'), ('Brain_Basal_Ganglia', 'Brain_Basal_Ganglia'), ('Brain_Cerebellum', 'Brain_Cerebellum'), ('Brain_Other', 'Brain_Other'), ('Breast', 'Breast'), ('Colon_Sigmoid', 'Colon_Sigmoid'), ('Colon_Transverse', 'Colon_Transverse'), ('Esophagus_Mucosa', 'Esophagus_Mucosa'), ('Esophagus_Muscularis', 'Esophagus_Muscularis'), ('Fibroblast_Cell_Line', 'Fibroblast_Cell_Line'), ('Gastroesophageal_Junction', 'Gastroesophageal_Junction'), ('Heart_Atrial_Appendage', 'Heart_Atrial_Appendage'), ('Heart_Left_Ventricle', 'Heart_Left_Ventricle'), ('Intestine_Terminal_Ileum', 'Intestine_Terminal_Ileum'), ('Kidney_Cortex', 'Kidney_Cortex'), ('Lymphoblastoid_Cell_Line', 'Lymphoblastoid_Cell_Line'), ('Minor_Salivary_Gland', 'Minor_Salivary_Gland'), ('Liver', 'Liver'), ('Lung', 'Lung'), ('Ovary', 'Ovary'), ('Pancreas', 'Pancreas'), ('Pituitary', 'Pituitary'), ('Prostate', 'Prostate'), ('Skeletal_Muscle', 'Skeletal_Muscle'), ('Skin', 'Skin'), ('Spleen', 'Spleen'), ('Stomach', 'Stomach'), ('Testis', 'Testis'), ('Thyroid', 'Thyroid'), ('Tibial_Nerve', 'Tibial_Nerve'), ('Uterus', 'Uterus'), ('Vagina', 'Vagina'), ('Whole_Blood', 'Whole_Blood')], max_length=200),
        ),
        migrations.AlterField(
            model_name='compmod',
            name='comp2',
            field=models.CharField(choices=[('ACC', 'ACC'), ('BLCA', 'BLCA'), ('CHOL', 'CHOL'), ('COAD', 'COAD'), ('DLBC', 'DLBC'), ('ESCA', 'ESCA'), ('GBM', 'GBM'), ('HNSC', 'HNSC'), ('KICH', 'KICH'), ('KIRC', 'KIRC'), ('KIRP', 'KIRP'), ('LAML', 'LAML'), ('LGG', 'LGG'), ('LIHC', 'LIHC'), ('LUAD', 'LUAD'), ('LUSC', 'LUSC'), ('MESO', 'MESO'), ('PAAD', 'PAAD'), ('PCPG', 'PCPG'), ('READ', 'READ'), ('SARC', 'SARC'), ('SKCM', 'SKCM'), ('STAD', 'STAD'), ('THCA', 'THCA'), ('THYM', 'THYM'), ('UVM', 'UVM')], max_length=200),
        ),
    ]
