# Generated by Django 3.0.2 on 2021-05-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0212_auto_20210519_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compmod',
            old_name='comp1',
            new_name='comp11',
        ),
        migrations.RenameField(
            model_name='compmod',
            old_name='comp2',
            new_name='comp22',
        ),
    ]
