# Generated by Django 3.0.2 on 2021-05-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0213_auto_20210523_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compmod',
            old_name='comp11',
            new_name='comp1',
        ),
        migrations.RenameField(
            model_name='compmod',
            old_name='comp22',
            new_name='comp2',
        ),
        migrations.RenameField(
            model_name='difftarmod',
            old_name='comp1',
            new_name='comp11',
        ),
        migrations.RenameField(
            model_name='difftarmod',
            old_name='comp2',
            new_name='comp22',
        ),
    ]
