# Generated by Django 3.0.2 on 2021-05-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0214_auto_20210523_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compmod',
            name='comp2',
            field=models.CharField(choices=[('ACC', 'hello'), ('BLCA', 'BLCA'), ('CHOL', 'CHOL'), ('COAD', 'COAD'), ('DLBC', 'DLBC'), ('ESCA', 'ESCA'), ('GBM', 'GBM'), ('HNSC', 'HNSC'), ('KICH', 'KICH'), ('KIRC', 'KIRC'), ('KIRP', 'KIRP'), ('LAML', 'LAML'), ('LGG', 'LGG'), ('LIHC', 'LIHC'), ('LUAD', 'LUAD'), ('LUSC', 'LUSC'), ('MESO', 'MESO'), ('PAAD', 'PAAD'), ('PCPG', 'PCPG'), ('READ', 'READ'), ('SARC', 'SARC'), ('SKCM', 'SKCM'), ('STAD', 'STAD'), ('THCA', 'THCA'), ('THYM', 'THYM'), ('UVM', 'UVM')], max_length=200),
        ),
    ]
