# Generated by Django 3.0.2 on 2021-05-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0216_auto_20210527_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difftarmod',
            name='comp22',
            field=models.CharField(choices=[('ACC', 'Adrenocortical carcinoma - ACC'), ('BLCA', 'Bladder Urothelial Carcinoma - BLCA'), ('CHOL', 'Cholangiocarcinoma - CHOL'), ('COAD', 'Colon adenocarcinoma - COAD'), ('DLBC', 'Lymphoid Neoplasm Diffuse Large B-cell Lymphoma - DLBC'), ('ESCA', 'Esophageal carcinoma - ESCA'), ('GBM', '\tGlioblastoma multiforme - GBM'), ('HNSC', 'Head and Neck squamous cell carcinoma - HNSC'), ('KICH', 'Kidney Chromophobe - KICH'), ('KIRC', 'Kidney renal clear cell carcinoma - KIRC'), ('KIRP', 'Kidney renal papillary cell carcinoma - KIRP'), ('LAML', 'Acute Myeloid Leukemia - LAML'), ('LGG', 'Brain Lower Grade Glioma - LGG'), ('LIHC', 'Liver hepatocellular carcinoma - LIHC'), ('LUAD', 'Lung adenocarcinoma - LUAD'), ('LUSC', '\tLung squamous cell carcinoma - LUSC'), ('MESO', 'Mesothelioma - MESO'), ('PAAD', 'Pancreatic adenocarcinoma - PAAD'), ('PCPG', 'Pheochromocytoma and Paraganglioma - PCPG'), ('READ', 'Rectum adenocarcinoma - READ'), ('SARC', 'Sarcoma - SARC'), ('SKCM', 'Skin Cutaneous Melanoma - SKCM'), ('STAD', 'Stomach adenocarcinoma - STAD'), ('THCA', 'Thyroid carcinoma - THCA'), ('THYM', 'Thymoma - THYM'), ('UVM', 'Uveal Melanoma - UVM')], max_length=200),
        ),
    ]
