# Generated by Django 3.0.2 on 2021-05-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0218_auto_20210527_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='druglanding',
            name='indication',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='druglanding',
            name='moa',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
