# Generated by Django 3.0.2 on 2022-02-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0220_auto_20210605_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('idd', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('supcode', models.CharField(max_length=200)),
                ('supname', models.CharField(max_length=200)),
                ('iid', models.CharField(max_length=200)),
                ('datac', models.CharField(max_length=200)),
            ],
        ),
    ]
