# Generated by Django 3.0.2 on 2022-03-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0222_auto_20220221_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celllanding',
            name='cancerLink',
        ),
    ]
