# Generated by Django 3.0.2 on 2022-03-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0224_auto_20220328_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='egret',
            name='cleanname1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
