# Generated by Django 3.0.2 on 2022-03-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0226_egret_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='egret',
            name='reflink',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
