# Generated by Django 3.0.2 on 2022-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0228_auto_20220329_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='celllanding',
            name='eqtl',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celllanding',
            name='genotype',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celllanding',
            name='qbic',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
