# Generated by Django 3.0.2 on 2022-03-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0231_auto_20220330_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='celllanding',
            name='refs3',
            field=models.URLField(default='#'),
        ),
    ]
