# Generated by Django 3.0.2 on 2022-03-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0232_celllanding_refs3'),
    ]

    operations = [
        migrations.AddField(
            model_name='celllanding',
            name='cancerLink',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
