# Generated by Django 3.0.2 on 2022-04-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0233_celllanding_cancerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='egret',
            name='diffexp',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='egret',
            name='diffexpgenes',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='egret',
            name='difftar',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='egret',
            name='difftargenes',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='egret',
            name='presexp',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
