# Generated by Django 3.0.2 on 2022-06-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0234_auto_20220401_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druglanding',
            name='avggenetar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='druglanding',
            name='avgtftar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='druglanding',
            name='nsamples',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='genelanding',
            name='pr_gene_id',
            field=models.FloatField(default=0),
        ),
    ]
