# Generated by Django 3.0.2 on 2022-07-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0235_auto_20220623_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='celllanding',
            name='datalink',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celllanding',
            name='vis',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
