# Generated by Django 3.2.5 on 2023-07-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0238_tissuesampleegret_cleanname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celllanding',
            name='refs',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='tissuelanding',
            name='refs',
            field=models.URLField(default='#'),
        ),
    ]
