# Generated by Django 3.2.5 on 2024-07-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0239_auto_20230724_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gse197sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=200)),
                ('geo', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('subtype', models.URLField()),
                ('mutation', models.URLField()),
                ('death', models.CharField(max_length=200)),
                ('survival', models.CharField(max_length=200)),
                ('estrogen', models.CharField(max_length=200)),
                ('her2', models.CharField(max_length=200)),
            ],
        ),
    ]
