# Generated by Django 3.2.5 on 2024-07-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0240_gse197sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerlanding',
            name='regulator',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
