# Generated by Django 3.2.5 on 2024-07-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0241_cancerlanding_regulator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gse197sample',
            old_name='geo',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='gse197sample',
            name='geoid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gse197sample',
            name='time_to_event',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gse197sample',
            name='tumor_location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gse197sample',
            name='vital_status',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
