# Generated by Django 3.2.5 on 2024-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0243_auto_20240720_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='gse197sample',
            name='sampleclean',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
