# Generated by Django 3.2.5 on 2024-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0244_gse197sample_sampleclean'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tissuesamplethy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleid', models.CharField(max_length=600)),
                ('subjectid', models.CharField(max_length=600)),
                ('tissueid', models.CharField(max_length=600)),
                ('gender', models.CharField(max_length=600)),
                ('age', models.CharField(max_length=600)),
                ('dthhrdy', models.CharField(max_length=600)),
                ('smatsscr', models.CharField(max_length=600)),
                ('smrin', models.CharField(max_length=600)),
                ('smts', models.CharField(max_length=600)),
                ('smtsd', models.CharField(max_length=600)),
                ('smubrid', models.CharField(max_length=600)),
                ('smtsisch', models.CharField(max_length=600)),
                ('grdid', models.CharField(max_length=600)),
                ('size', models.CharField(max_length=600)),
                ('link', models.CharField(max_length=600)),
                ('smtstptref', models.CharField(max_length=600)),
                ('smmncpb', models.CharField(max_length=600)),
                ('smgnsdtc', models.CharField(max_length=600)),
                ('cleanname', models.CharField(max_length=600)),
            ],
        ),
    ]
