# Generated by Django 3.2.5 on 2024-08-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0245_tissuesamplethy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissue',
            name='reftool4',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissue',
            name='tool4',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
