# Generated by Django 3.2.5 on 2024-08-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0246_auto_20240801_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuesamplethy',
            name='proxage',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
