# Generated by Django 3.2.5 on 2024-08-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0247_tissuesamplethy_proxage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuelanding',
            name='cardtissue',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
