# Generated by Django 3.2.5 on 2024-08-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0248_tissuelanding_cardtissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuelanding',
            name='motif2',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tissuelanding',
            name='motifDesc2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
