# Generated by Django 3.2.5 on 2024-08-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0249_auto_20240816_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='tissuesamplethy',
            name='decsex',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
