# Generated by Django 3.2.5 on 2024-11-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0250_tissuesamplethy_decsex'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancer',
            name='nnets3',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancer',
            name='nnets3ref',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
