# Generated by Django 3.2.5 on 2024-12-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0251_auto_20241110_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerpheno',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancerpheno',
            name='size',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
