# Generated by Django 3.2.5 on 2024-12-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0252_auto_20241210_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerpheno',
            name='ss',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
