# Generated by Django 3.2.5 on 2024-12-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0253_cancerpheno_ss'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerpheno',
            name='submitter_id_clean',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
