# Generated by Django 3.2.5 on 2024-12-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0254_cancerpheno_submitter_id_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='breastsample',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breastsample',
            name='size',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breastsample',
            name='ss',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breastsample',
            name='submitter_id_clean',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liversample',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liversample',
            name='size',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liversample',
            name='ss',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liversample',
            name='submitter_id_clean',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
