# Generated by Django 3.2.5 on 2024-12-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0255_auto_20241214_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='pancreassample',
            name='link2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pancreassample',
            name='size2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
