# Generated by Django 3.2.5 on 2024-12-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandapp', '0258_pancreassample_submitter_id_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcgasample',
            name='link2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcgasample',
            name='size2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcgasample',
            name='ss',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcgasample',
            name='submitter_id_clean',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
